version: '3.9'

services:
  m347-kn04b-db:
    image: mariadb:latest
    container_name: m347-kn04b-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: password
    networks:
      kn04-netz:
        ipv4_address: 172.10.5.10

  m347-kn04b-web:
    image: leonaistrefitbz/m347:kn04b-web-1
    container_name: m347-kn04b-web
    ports:
      - "80:80"
    depends_on:
      - m347-kn04b-db
    networks:
      kn04-netz:
        ipv4_address: 172.10.5.11

    environment:
      DB_HOST: m347-kn04b-db
      DB_NAME: testdb
      DB_USER: root
      DB_PASS: root


networks:
  kn04-netz:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16
          ip_range: 172.10.5.0/24
          gateway: 172.10.5.254